// angular/laptop-holder/src/app/app.component.ts
import { Component } from '@angular/core';
import { BitByBitBase } from '@bitbybit-dev/core';
import { OccStateEnum } from '@bitbybit-dev/occt-worker';
import { Scene, Engine, Color4, Color3, HemisphericLight, Vector3, ArcRotateCamera, Light } from '@babylonjs/core';
import { LaptopLogic } from './laptop';
class Laptop {
    id: string;
    width: number;
    height: number;
    length: number;
}

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css'],
})
export class AppComponent {

    bitbybit = new BitByBitBase()

    title = 'trialwebsite';
    showSpinner = true;
    bitbybitInitialised = false;

    prevLaptops: Laptop[];
    laptops: Laptop[] = [
        {
            id: Math.random().toString(),
            width: 30.41,
            length: 1.5,
            height: 21.24,
        }
    ]

    scene: Scene;
    engine: Engine;
    timePassedFromPreviousIteration = 0;

    private laptopService: LaptopLogic;

    renderLoopFunction = () => {
        this.scene.render();
    }

    ngOnInit() {
        const canvas = document.getElementById('renderCanvas') as HTMLCanvasElement;

        this.engine = new Engine(canvas);
        this.scene = new Scene(this.engine);
        this.engine.setHardwareScalingLevel(0.5);
        this.scene.clearColor = new Color4(26 / 255, 28 / 255, 31 / 255, 1);
        const camera = new ArcRotateCamera('Camera', 0, 10, 10, new Vector3(0, 0, 0), this.scene);
        camera.attachControl(canvas, true);

        const light = new HemisphericLight('HemiLight', new Vector3(0, 1, 0), this.scene);
        light.intensityMode = Light.INTENSITYMODE_ILLUMINANCE;
        light.intensity = 1;
        this.scene.metadata = { shadowGenerators: [] };

        const occt = new Worker(new URL('./occ.worker', import.meta.url), { name: 'OCC', type: 'module' })
        const jscad = new Worker(new URL('./jscad.worker', import.meta.url), { name: 'JSCAD', type: 'module' })

        this.bitbybit.init(this.scene, occt, jscad);

        this.bitbybit.occtWorkerManager.occWorkerState$.subscribe(s => {
            if (s.state === OccStateEnum.initialised) {
                this.showSpinner = false;
                this.bitbybitInitialised = true;
                this.engine.resize();
                this.laptopService = new LaptopLogic(this.bitbybit);
                this.laptopService.do();
            } else if (s.state === OccStateEnum.computing) {
                this.showSpinner = true;
            } else if (s.state === OccStateEnum.loaded) {
                this.showSpinner = false;
            }
        });

        this.engine.runRenderLoop(this.renderLoopFunction);

        window.onresize = () => {
            if (this.engine) {
                this.engine.resize();
            }
        }
    }

    async jscadDrawBox() {
        const cube = await this.bitbybit.occt.shapes.solid.createBox({ width: 2, length: 2, height: 2, center: [0, 0, 0] });
        await this.bitbybit.draw.drawAnyAsync({ entity: cube, options: undefined });
    }

    render() {
        if (!this.prevLaptops || this.laptopsNotTheSame(this.prevLaptops, this.laptops)) {
            this.laptopService.render(this.laptops);
            this.prevLaptops = [...this.laptops.map(l => ({ ...l }))];
        }
    }

    downloadStep() {
        this.laptopService.downloadStep();
    }

    downloadStl() {
        this.laptopService.downloadStl();
    }

    laptopWidthChanged(val, laptop: Laptop) {
        laptop.width = val;
    }

    laptopLengthChanged(val, laptop: Laptop) {
        laptop.length = val;
    }

    laptopHeightChanged(val, laptop: Laptop) {
        laptop.height = val;
    }

    add() {
        this.laptops.push({
            id: Math.random().toString(),
            width: 30.41,
            length: 1.5,
            height: 21.24,
        });
        this.render();
    }

    remove(laptop) {
        this.laptops = this.laptops.filter(s => s.id !== laptop.id);
        this.render();
    }


    private laptopsNotTheSame(prev: Laptop[], current: Laptop[]) {
        let result = false;
        if (prev.length !== current.length) {
            result = true;
        } else {
            this.prevLaptops.forEach((c) => {
                const laptop = this.laptops.find(s => s.id === c.id);
                if (!laptop) {
                    result = true;
                } else if (laptop.width !== c.width || laptop.height !== c.height || laptop.length !== c.length) {
                    result = true;
                }
            })
        }
        return result;
    }


}

<div class="main">
    <div [ngClass]="{'hidden': !this.showSpinner}" class="lds-ripple">
        <div></div>
        <div></div>
    </div>
    <canvas [ngClass]="{'opaque': !this.bitbybitInitialised}" id="renderCanvas" class="example-sidenav-content">
    </canvas>
</div>
<div class="content">

    <div class="explanation">
        <h1>LAPTOP HOLDER</h1>
        <h2>Configurator</h2>
        <div class="scrolling">
            <p>
                <img width="100%" src="assets/lapholders1.jpeg" />
            </p>
            <p>
                The application allows you to configure custom multi slot laptop holder. Choose how many laptops you
                want and adjust the basic dimensions. Save your file and use it for 3D printing.
            </p>
            <p>
                This application also serves as an example which demonstrates possibilities to integrate Bit by bit
                developers
                platform in
                your own websites, configurators or webshops. We have recently released our core algorithms as an <a
                    href="https://www.npmjs.com/package/bitbybit-core" target="_blank">npm package</a>.
                If you are the beginner you can use our <a href="https://bitbybit.dev" target="_blank">bitbybit.dev</a>
                platform to learn to use the API and construct parametric geometries.
                If you are professional, consider exploring our <a href="docs.bitbybit.dev" target="_blank">bitbybit.dev
                    API</a>.
            </p>
            <p>
                By downloading STEP file you can easily 3D print it. To understand how to do that and learn how the
                script works you can enroll in this free course on our school at <a
                    href="https://school.bitbybit.dev/p/programming-vertical-laptop-holder-in-typescript"
                    target="_blank">school.bitbybit.dev</a>
            </p>
        </div>
    </div>
    <div class="space"></div>
    <div class="interaction" [ngClass]="{'opaque': !this.bitbybitInitialised}">
        <div>
            <ng-container *ngFor="let laptop of laptops; let i = index">
                <div>
                    Laptop Nr. {{i + 1}}
                    <button class="delete" color="primary" mat-flat-button (click)="remove(laptop)" aria-label="Delete">
                        <mat-icon>delete</mat-icon>
                    </button>
                </div>
                <div class="input">
                    <mat-form-field class="example-full-width" appearance="fill">
                        <mat-label>Width</mat-label>
                        <input (blur)="render()" type="number" matInput #message maxlength="10"
                            [(ngModel)]="laptop.width">
                    </mat-form-field>
                </div>
                <div class="input">
                    <mat-form-field appearance="fill">
                        <mat-label>Length</mat-label>
                        <input (blur)="render()" type="number" matInput #message maxlength="10"
                            [(ngModel)]="laptop.length">
                    </mat-form-field>
                </div>
                <div class="input">
                    <mat-form-field class="example-full-width" appearance="fill">
                        <mat-label>Height</mat-label>
                        <input (blur)="render()" type="number" matInput #message maxlength="10"
                            [(ngModel)]="laptop.height">
                    </mat-form-field>
                </div>
            </ng-container>
        </div>
        <br>
        <div>
            <button mat-raised-button color="primary" (click)="add()" aria-label="Example icon button with a menu icon">
                Add Laptop
            </button>
            <button class="download" mat-raised-button color="primary" (click)="downloadStep()"
                aria-label="Example icon button with a menu icon">
                Download STEP
            </button>
            <button class="download" mat-raised-button color="primary" (click)="downloadStl()"
                aria-label="Example icon button with a menu icon">
                Download STL
            </button>
        </div>
    </div>
</div>

// react/cup/src/App.tsx
import React, { useEffect, useState } from 'react';
import './App.css';
import { BitByBitBase, OccStateEnum } from 'bitbybit-core';
import { Scene, Engine, Color4, HemisphericLight, Vector3, ArcRotateCamera, Light } from '@babylonjs/core';
import { CupLogic } from './cup';
import { Button, Slider } from '@mui/material';

function App() {

    const [showSpinner, setShowSpinner] = useState<boolean>(true);
    const [bitByBitInitialised, setBitByBitInitialised] = useState<boolean>(false);

    const [cupLogic, setCupLogic] = useState<CupLogic>(undefined);

    const [cupHeight, setCupHeight] = useState<number>(13);
    const [cupRadius, setCupRadius] = useState<number>(4.5);
    const [cupThickness, setCupThickness] = useState<number>(1);
    const [cupHandleDistance, setHandleDistance] = useState<number>(2);
    const [cupHandleHeight, setHandleHeight] = useState<number>(0.5);

    useEffect(() => {

        const bitbybit = new BitByBitBase();
        const canvas = document.getElementById('renderCanvas') as HTMLCanvasElement;

        const engine = new Engine(canvas);
        const scene = new Scene(engine);
        engine.setHardwareScalingLevel(0.5);
        scene.clearColor = new Color4(26 / 255, 28 / 255, 31 / 255, 1);
        const camera = new ArcRotateCamera('Camera', 0, 10, 10, new Vector3(0, 0, 0), scene);
        camera.attachControl(canvas, true);

        const light = new HemisphericLight('HemiLight', new Vector3(0, 1, 0), scene);
        light.intensityMode = Light.INTENSITYMODE_ILLUMINANCE;
        light.intensity = 1;
        scene.metadata = { shadowGenerators: [] };

        const occt = new Worker(new URL('./occ.worker', import.meta.url), { name: 'OCC', type: 'module' })

        bitbybit.init(scene, occt, undefined);

        engine.runRenderLoop(() => {
            scene.render();
        });

        window.onresize = () => {
            if (engine) {
                engine.resize();
            }
        }

        bitbybit.occtWorkerManager.occWorkerState$.subscribe(s => {
            if (s.state === OccStateEnum.initialised) {
                setShowSpinner(false);
                setBitByBitInitialised(true);
                engine.resize();
                const cl = new CupLogic(bitbybit);

                engine.runRenderLoop(() => {
                    scene.render();
                });
                cl.initScene(engine);
                setCupLogic(cl)
                cl.compute(cupHeight, cupRadius, cupThickness, cupHandleDistance, cupHandleHeight);
            } else if (s.state === OccStateEnum.computing) {
                setShowSpinner(true);
            } else if (s.state === OccStateEnum.loaded) {
                setShowSpinner(false);
            }
        });
    }, [])

    const downloadStep = () => {
        cupLogic.downloadStep();
    }

    const downloadStl = () => {
        cupLogic.downloadStl();
    }

    const recompute = () => {
        if (!showSpinner) {
            cupLogic.compute(cupHeight, cupRadius, cupThickness, cupHandleDistance, cupHandleHeight)
        }
    }

    return (
        <div className="App">
            <div className="main">
                {showSpinner &&
                    <div className="lds-ripple">
                        <div></div>
                        <div></div>
                    </div>
                }
                <canvas id="renderCanvas" className={bitByBitInitialised ? '' : 'opaque'}>
                </canvas>
            </div>
            <div className="content">
                <div className="explanation">
                    <h1>CUP</h1>
                    <h2>Configurator</h2>
                    <div className="scrolling">
                        <p>
                            The application allows you to configure a custom cup for your coffee or tea. Choose any combination of parameters to get proprtions that you want. Save your file and use it for 3D printing.
                        </p>
                        <p>
                            This application also serves as an example which demonstrates possibilities to integrate Bit by bit developers
                            platform in
                            your own websites, configurators or webshops. We have recently released our core algorithms as an <a rel="noreferrer" href="https://www.npmjs.com/package/bitbybit-core" target="_blank">npm package</a>.
                            If you are the beginner you can use our <a rel="noreferrer" href="https://bitbybit.dev" target="_blank">bitbybit.dev</a> platform to learn to use the API and construct parametric geometries.
                            If you are professional, consider exploring our <a href="docs.bitbybit.dev" rel="noreferrer" target="_blank">bitbybit.dev API</a>.
                        </p>
                        <p>
                            By downloading STEP file you can easily 3D print it.
                        </p>
                    </div>
                </div>
                <div className="space"></div>
                <div className="interaction" >
                    <div>
                        <h2>
                            Cup Parameters
                        </h2>
                        <div className="input">
                            <h3>Cup Height ({cupHeight} cm )</h3>
                            <Slider disabled={showSpinner} aria-label="Height"
                                valueLabelDisplay="auto"
                                step={0.01} min={6} max={16} value={cupHeight}
                                onChange={(e) => setCupHeight(+(e.target as any).value)} onChangeCommitted={recompute}
                            />
                        </div>
                        <div className="input">
                            <h3>Cup Radius ({cupRadius} cm )</h3>
                            <Slider disabled={showSpinner} aria-label="Radius"
                                valueLabelDisplay="auto"
                                step={0.01} min={3} max={8} value={cupRadius}
                                onChange={(e) => setCupRadius(+(e.target as any).value)} onChangeCommitted={recompute}
                            />
                        </div>
                        <div className="input">
                            <h3>Cup Thickness ({cupThickness} cm )</h3>
                            <Slider disabled={showSpinner} aria-label="Thickness"
                                valueLabelDisplay="auto"
                                step={0.01} min={0.5} max={1} value={cupThickness}
                                onChange={(e) => setCupThickness(+(e.target as any).value)} onChangeCommitted={recompute}
                            />
                        </div>
                        <div className="input">
                            <h3>Handle Length ({cupHandleDistance} cm)</h3>
                            <Slider disabled={showSpinner} aria-label="Handle Length"
                                valueLabelDisplay="auto"
                                step={0.01} min={0.3} max={cupRadius} value={cupHandleDistance}
                                onChange={(e) => setHandleDistance(+(e.target as any).value)} onChangeCommitted={recompute}
                            />
                        </div>
                        <div className="input">
                            <h3>Handle Height ({cupHandleHeight})</h3>
                            <Slider disabled={showSpinner} aria-label="Handle Height"
                                valueLabelDisplay="auto"
                                step={0.01} min={0} max={1} value={cupHandleHeight}
                                onChange={(e) => setHandleHeight(+(e.target as any).value)} onChangeCommitted={recompute}
                            />
                        </div>
                        <div className="actions">
                            <Button disabled={showSpinner} variant="contained" onClick={downloadStep}>Download STEP</Button>
                            <Button disabled={showSpinner} variant="contained" onClick={downloadStl}>Download STL</Button>
                        </div>
                    </div>

                </div >
            </div >
        </div >
    );
}

export default App;
